services:
    danieltj.reportuser.controller.ext:
        class: danieltj\reportuser\controller\ext
        arguments:
            - '@controller.helper'
            - '@dispatcher'
            - '@language'
            - '@notification_manager'
            - '@request'
            - '@routing.helper'
            - '@template'
            - '@user'
            - '@danieltj.reportuser.includes.functions'

    danieltj.reportuser.controller.mcp:
        class: danieltj\reportuser\controller\mcp
        arguments:
            - '@auth'
            - '@controller.helper'
            - '@dispatcher'
            - '@language'
            - '@notification_manager'
            - '@pagination'
            - '@request'
            - '@routing.helper'
            - '@template'
            - '@user'
            - '@danieltj.reportuser.includes.functions'

    danieltj.reportuser.listener:
        class: danieltj\reportuser\event\listener
        arguments:
            - '@auth'
            - '@language'
            - '@request'
            - '@routing.helper'
            - '@template'
            - '@user'
            - '@danieltj.reportuser.includes.functions'
        tags:
            - { name: event.listener }

    danieltj.reportuser.includes.functions:
        class: danieltj\reportuser\includes\functions
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@dispatcher'
            - '@language'
            - '@log'
            - '@notification_manager'
            - '@routing.helper'
            - '@user'
            - '%datetime.class%'

    danieltj.reportuser.notification.type.new_report:
        class: danieltj\reportuser\notification\type\new_report
        parent: notification.type.base
        shared: false
        tags: [ { name: notification.type } ]
        calls:
            - [ 'set_user_loader', [ '@user_loader' ] ]
            - [ 'set_functions', [ '@danieltj.reportuser.includes.functions' ] ]

    danieltj.reportuser.notification.type.report_closed:
        class: danieltj\reportuser\notification\type\report_closed
        parent: notification.type.base
        shared: false
        tags: [ { name: notification.type } ]
        calls:
            - [ 'set_user_loader', [ '@user_loader' ] ]
            - [ 'set_functions', [ '@danieltj.reportuser.includes.functions' ] ]

    danieltj.reportuser.notification.type.request_changes:
        class: danieltj\reportuser\notification\type\request_changes
        parent: notification.type.base
        shared: false
        tags: [ { name: notification.type } ]
        calls:
            - [ 'set_user_loader', [ '@user_loader' ] ]
            - [ 'set_functions', [ '@danieltj.reportuser.includes.functions' ] ]
