services:
    danieltj.reportuser.controller.ext:
        class: danieltj\reportuser\controller\ext
        arguments:
            - '@controller.helper'
            - '@language'
            - '@request'
            - '@routing.helper'
            - '@template'
            - '@user'
            - '@danieltj.reportuser.includes.functions'

    danieltj.reportuser.controller.mcp:
        class: danieltj\reportuser\controller\mcp
        arguments:
            - '@danieltj.reportuser.includes.functions'

    danieltj.reportuser.listener:
        class: danieltj\reportuser\event\listener
        arguments:
            - '@language'
            - '@routing.helper'
            - '@template'
            - '@danieltj.reportuser.includes.functions'
        tags:
            - { name: event.listener }

    danieltj.reportuser.includes.functions:
        class: danieltj\reportuser\includes\functions
        arguments:
            - '@auth'
            - '@dbal.conn'
            - '@routing.helper'
            - '@user'
